[workspace]
members = [
    "mailman",
    "mailman-dummy",
    "mailman-tcp",
    "mailman-udp",
    "mailman-http",
    "mailman-webworker",
    "mailman-websocket",
    "mailman-webrtc-datachannel",
]
