[workspace]
members = [
    "mezzenger",
    "mezzenger-tcp",
    "mezzenger-udp",
    "mezzenger-dtls",
    "mezzenger-http",
    "mezzenger-webworker",
    "mezzenger-websocket",
    "mezzenger-webrtc-datachannel",
]
exclude = ["mezzenger-tests"]
